GET http://localhost:9876/secure
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJjMWZPa25jY0tEdkdLQ3l6aDlLLV9kWkVBV0hSMVVtd2NKeHk0N1lfZDdzIn0.eyJleHAiOjE1OTY5NzM5ODAsImlhdCI6MTU5Njk3MzkyMCwianRpIjoiYzJmZGQ2YWMtMmM1Yy00MDY2LWE1YjYtMDhhODQzZGI5MWNmIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2F1dGgvcmVhbG1zL21hc3RlciIsInN1YiI6ImU1OWJhMWQ0LWU3OWQtNDIyZC1iNzRhLTAyM2Y2MGE5YmQ1MiIsInR5cCI6IkJlYXJlciIsImF6cCI6ImFkbWluLWNsaSIsInNlc3Npb25fc3RhdGUiOiJhMTRmY2M4Ni01ZjIyLTQzMGUtODFkZS0zYmFiYjlmYmIyZTYiLCJhY3IiOiIxIiwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbiJ9.Uhti7gNN0YdLlOXEiKpFs2AbhLdUaUz559EduCLVBWsASpRFAgJ6jxjY7912evv2ieKvd9Xv28oh4sj-0uEej2jCt1sm0SbLuZuEYDUv4a-9bvZ2byC11s_L7b5xZxZKvs8VvoF1J2pQJgIHvksrWPuGglaWbk3CN0Ge2A4LN81ScVIecO9wACN3pEd7GJhePVpImkUmEWrdbU1ftZMhHTBSO0E_OIxk0-NrAIg4e9Uh7Qzi05ZHvnaHHlqQtQCztlZHr3Y7CDQ6k--N1JaPOqzcyQ8-kV2D26O_jqDyCs3wvLXb0Rre0SseINLS7SHtfemCacxkm1KHZwpDOHgPdg

###

