name: Build

on:
  push:
    branches: [ master, dotty ]
  pull_request:
    branches: [ master, dotty ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-scala
        path: | 
          ~/.ivy2/cache
          ~/.sbt
          ~/embedded-keycloak/
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Compile and run tests
      run: sbt ";example/compile; akka-http-jwt-auth/test; akka-http-oidc-client/test; akka-http-client-circe/test;"
