# This workflow will launch at 01:00 every MON,WED,FRI
on:
  schedule:
    - cron: '0 0 1 ? * MON,WED,FRI *'
  workflow_dispatch:

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Launch Scala Steward
    steps:
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}